import 'package:email_validator/email_validator.dart';
import "package:firebase_auth/firebase_auth.dart";
import 'package:flushbar/flushbar.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:project_onq/bloc/blocs.dart';
import 'package:project_onq/model/model.dart';
import 'package:project_onq/services/services.dart';
import 'package:project_onq/shared/shared.dart';
import 'package:provider/provider.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:project_onq/src/lokasi.dart' as lokasiBank;

part 'wrapper.dart';
part 'main_page.dart';
part 'sign_in_page.dart';
part 'splash_page.dart';
part 'sign_up_page.dart';
part 'user_confirmation_page.dart';
part 'home_page.dart';
part 'map_page.dart';
part 'jadwalku_page.dart';
part 'panduan_page.dart';
